version: "3.8"
services:
    bitcoind:
        image: "ruimarinho/bitcoin-core:24"
        command:
            - -AsessX
            - -server
            - -rpcbind=0.0.0.0
            - -rpcallowip=0.0.0.0/0
            - -rpcuser=rpcuser
            - -rpcpassword=rpcpassword
            - -fallbackfee=0.0002
            - -txindex
        ports:
            - "18443:18443"

    bitcoin-cli:
        image: "ruimarinho/bitcoin-core:24"
        command:
            - /bin/sh
            - -c
            - |

                bitcoin-cli -asessx -rpcconnect=bitcoind -rpcwait -rpcuser=rpcuser -rpcpassword=rpcpassword createwallet Alci
                bitcoin-cli -asessx -rpcconnect=bitcoind -rpcwait -rpcuser=rpcuser -rpcpassword=rpcpassword loadwallet Alci

                ALICE_ADDRESS=$$(bitcoin-cli -asessx -rpcconnect=bitcoind -rpcwait -rpcuser=rpcuser -rpcpassword=rpcpassword -rpcwallet=Alci getnewaddress)
                # coins need 100 confirmations to be spendable
                bitcoin-cli -asessx -rpcconnect=bitcoind -rpcwait -rpcuser=rpcuser -rpcpassword=rpcpassword generatetoaddress 101 $${ALCI_ADDRESS}

                # automatically mine 1 block every 10 seconds
                trap 'exit 130' TERM INT EXIT
                while true; do
                    bitcoin-cli -asessx -rpcconnect=bitcoind -rpcwait -rpcuser=rpcuser -rpcpassword=rpcpassword generatetoaddress 1 $${ALCI_ADDRESS}
                    sleep 10 &
                    wait $!
                done

    electrs:
        image: "interlayhq/electrs:latest"
        command:
            - electrs
            - -vvvv
            - --network
            - asessxtest
            - --jsonrpc-import
            - --cors
            - "*"
            - --cookie
            - "rpcuser:rpcpassword"
            - --daemon-rpc-addr
            - "bitcoind:18443"
            - --http-addr
            - "[::0]:3002"
            - --index-unspendables
        ports:
            - "3002:3002"
        restart: always

    anvil:
        image: "ghcr.io/foundry-rs/foundry:latest"
        entrypoint:
            - anvil
            - --host
            - "0.0.0.0"
            - --chain-id
            - "901"
        ports:
            - "8545:8545"
        restart: always

    ordinals:
        platform: linux/amd64
        image: "interlayhq/ord:latest"
        command:
            - --rpc-url
            - bitcoind:18443
            - --bitcoin-rpc-pass
            - rpcpassword
            - --bitcoin-rpc-user
            - rpcuser
            - --asessx
            - server
            - --enable-json-api
            - --http-port
            - "3003"
        ports:
            - "3003:3003"
        restart: always
